### ISSUE TITLE
Is it possible to restore bricked V-SOL XPON V2801F

### ISSUE THREAD

**Issue by vbaskoff** [Anime4000/RTL960x#304]
Hi Folks,

Without any reason sfp onu (V-SOL XPON V2801F) stopped to be reachable via IP, no mac address appeared behind sfp port in arp table as well.

RouterOS 'see' physical presence of the module and mark port as running.

Any way to bring it back to life?

`
[admin@MikroTik] > /interface/ethernet/monitor sfp5

# 1970-01-02 01:55:01 by RouterOS 7.12.1
# software id = 0MDF-UTYM
#
                      name: sfp5
                    status: link-ok
          auto-negotiation: done
                      rate: 1Gbps
               full-duplex: yes
           tx-flow-control: no
           rx-flow-control: no
                 supported: 10M-baseT-half,10M-baseT-full,100M-baseT-half,
                            100M-baseT-full,1G-baseT-half,1G-baseT-full,
                            1G-baseX
               advertising: 
  link-partner-advertising: 
        sfp-module-present: yes
               sfp-rx-loss: yes
                  sfp-type: SFP/SFP+/SFP28/SFP56
           eeprom-checksum: bad
                    eeprom: 0000: 03 00 00 00 00 00 00 00  03 00 00 00 00 00 00 00  ........ ........
                            *
                            0080: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
                            *
`
![IMG_20240703_191904__01](https://github.com/Anime4000/RTL960x/assets/7298997/69a05128-a945-4001-b6f7-e278d9754bbc)

**Comment by Anime4000** [comment]
only can see is via TTL UART

**Comment by vbaskoff** [comment]
Does this sfp has some UART pins on the pcb?

**Comment by Anime4000** [comment]
the SFP pin doesn't, need to open it and pin on the SoC pinout

**Comment by crrodriguez** [comment]
I also have a "bricked" CarlitosPro stick which is the same device. Does not autoneg with any device I have.
 wrong LAN_SDS_MODE selected. Buying all the needed debug tools more expensive than new ODI stick.

**Comment by dittohead** [comment]
@vbaskoff did you fix your dongle? got similar issue with fd511gx, but wait for needle pad

**Comment by dittohead** [comment]
got same issue as @vbaskoff

```
/interface ethernet monitor sfp1  
                      name: sfp1
                    status: no-link
          auto-negotiation: done
               advertising: 
  link-partner-advertising: 
        sfp-module-present: yes
               sfp-rx-loss: no
           eeprom-checksum: bad
                    eeprom: 0000: 03 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
```

connect with uart sucessfuly, but can't do backup via uart
lan_sds_mode didn't help

@Anime4000 any ideas?
